const data = [
  {
    id: "dashboard",
    icon: "iconsminds-palette",
    label: "menu.dashboard",
    to: "/app/dashboard",
    check_permission: false,
    module_slug: "",
    permission_type: "",
  },
  {
    id: "subadmins",
    icon: "iconsminds-network",
    label: "menu.subadmins",
    to: "/app/subadmins",
    check_permission: true,
    module_slug: "subadmins",
    permission_type: "list",
  },
  {
    id: "users",
    icon: "iconsminds-mens",
    label: "menu.users",
    to: "/app/users",
    check_permission: true,
    module_slug: ["users", "drivers", "users"],
    permission_type: "list",
    subs: [
      {
        icon: "simple-icon-people",
        label: "menu.customers",
        to: "/app/customers",
      },
      {
        icon: "simple-icon-people",
        label: "menu.drivers",
        to: "/app/drivers",
      },
      {
        icon: "simple-icon-people",
        label: "menu.active-inactive-users",
        to: "/app/active-inactive-users",
      },
    ],
  },
  {
    id: "business_categories",
    icon: "iconsminds-box-with-folders",
    label: "menu.business-categories",
    to: "/app/business-categories",
    check_permission: true,
    module_slug: "business_categories",
    permission_type: "list",
  },
  {
    id: "product_categories",
    icon: "iconsminds-dice",
    label: "menu.product-categories",
    to: "/app/product-categories",
    check_permission: true,
    module_slug: ["product_categories", "product_sub_category"],
    module_routes: ["product_categories", "product_sub_category"],
    permission_type: "list",
    subs: [
      {
        icon: "simple-icon-grid",
        label: "menu.product-categories",
        to: "/app/product-categories",
      },
      {
        icon: "simple-icon-grid",
        label: "menu.product-subcategories",
        to: "/app/product-subcategories",
      },
    ],
  },
  {
    id: "product_customizations",
    icon: "simple-icon-layers",
    label: "menu.product-customizations",
    to: "/app/product-categories",
    check_permission: true,
    module_slug: ["product_customizations", "product_customizations_subtype"],
    permission_type: "list",
    subs: [
      {
        icon: "simple-icon-layers",
        label: "menu.customization-types",
        to: "/app/customization-types",
      },
      {
        icon: "simple-icon-layers",
        label: "menu.customization-subtypes",
        to: "/app/customization-subtypes",
      },
    ],
  },
  {
    id: "products",
    icon: "iconsminds-shopping-bag",
    label: "menu.products",
    to: "/app/products",
    check_permission: true,
    module_slug: "product",
    permission_type: "list",
  },
  {
    id: "brands",
    icon: "iconsminds-tag-3",
    label: "menu.brands",
    to: "/app/brands",
    check_permission: true,
    module_slug: "brand",
    permission_type: "list",
  },
  {
    id: "warehouses",
    icon: "iconsminds-clothing-store",
    label: "menu.warehouses",
    to: "/app/warehouses",
    check_permission: true,
    module_slug: "warehouse",
    permission_type: "list",
  },
  {
    id: "banners",
    icon: "iconsminds-blackboard",
    label: "menu.banners",
    to: "/app/banners",
    check_permission: true,
    module_slug: "banner",
    permission_type: "list",
  },
  {
    id: "dealofday",
    icon: "iconsminds-blackboard",
    label: "menu.dealofday",
    to: "/app/dealofday",
    check_permission: true,
    module_slug: "dealofday",
    permission_type: "list",
  },
  {
    id: "notifications",
    icon: "simple-icon-bell",
    label: "menu.notifications",
    to: "/app/notifications",
    check_permission: true,
    module_slug: "notification",
    permission_type: "add",
  },
  // {
  //   id: "coupons",
  //   icon: "iconsminds-gift-box",
  //   label: "menu.coupons",
  //   to: "/app/coupons",
  //   check_permission: true,
  //   module_slug: "coupons",
  //   permission_type: "list",
  // },
  {
    id: "orders",
    icon: "iconsminds-check",
    label: "menu.orders",
    to: "/app/orders",
    check_permission: true,
    module_slug: "orders",
    permission_type: "list",
  },
  {
    id: "transactions",
    icon: "iconsminds-dollar",
    label: "menu.transactions",
    to: "/app/transactions",
    check_permission: true,
    module_slug: "transaction",
    permission_type: "list",
  },
  {
    id: "contents",
    icon: "simple-icon-book-open",
    label: "menu.contents",
    to: "/app/contents",
    check_permission: true,
    module_slug: ["contents"],
    permission_type: "edit",
    subs: [
      {
        icon: "simple-icon-book-open",
        label: "menu.about-us",
        to: "/app/contents/about-us",
      },
      {
        icon: "simple-icon-book-open",
        label: "menu.privacy-policy",
        to: "/app/contents/privacy-policy",
      },
    ],
  },
  {
    id: "faqs",
    icon: "iconsminds-books",
    label: "menu.faqs",
    to: "/app/faqs",
    check_permission: true,
    module_slug: "faqs",
    permission_type: "list",
  },
  {
    id: "offers",
    icon: "iconsminds-money-bag",
    label: "menu.offers",
    to: "/app/offers",
    check_permission: true,
    module_slug: "offer",
    permission_type: "list",
  },
  {
    id: "reports",
    icon: "iconsminds-file-clipboard-file---text",
    label: "menu.reports",
    to: "/app/reports",
    check_permission: true,
    module_slug: ["report"],
    permission_type: "list",
    subs: [
      {
        icon: "simple-icon-book-open",
        label: "menu.reports-sale",
        to: "/app/settings/sale-report",
      },
      {
        icon: "simple-icon-book-open",
        label: "menu.reports-collection",
        to: "/app/settings/collection-report",
      },
      {
        icon: "simple-icon-book-open",
        label: "menu.reports-reconcilation",
        to: "/app/settings/reconcilation-report",
      },
      {
        icon: "simple-icon-book-open",
        label: "menu.reports-gst",
        to: "/app/settings/gst-report",
      },
    ],
  },
  {
    id: "settings",
    icon: "iconsminds-gear",
    label: "menu.settings",
    to: "/app/settings",
    check_permission: true,
    module_slug: ["setting"],
    permission_type: "edit",
    subs: [
      {
        icon: "simple-icon-book-open",
        label: "menu.settings",
        to: "/app/settings/normal-settings",
      },
      {
        icon: "simple-icon-book-open",
        label: "menu.delivery-settings",
        to: "/app/settings/delivery-settings",
      },
    ],
  },
];
export default data;
