'use strict';

module.exports ={
        "ADD_SUCCESS": "Created successfully",
        "AUTH_SUCCESS": "Authenticated Successfully",
        "AUTH_ERROR": "Authentication Failure",
        "EMAIL_REGISTERD_ERROR": "This Email Id is not registered to any account",
        "NO_DATA_FOUND": "No Data Found",
        "BAD_REQUEST": "Bad Request",
        "INVALID_DATA": "Invalid Data Provided.",
        "PASSWORD_RESET_EMAIL": "An Email has been sent to you to reset your password.",
        "UPDATE_SUCCESS": "Updated successfully.",
        "TOKEN_EXPIRED": "Token has been expired.",
        "WRONG_PASSWORD": "Old Password is wrong",
        "FETCH_SUCCESS": "Fetched successfully.",
        "ALREADY_REGISTERED_ACCOUNT": "This Account has been already registered.",
        "ACCOUNT_CREATED": "Account created",
        "OTP_EXPIRED": "Your OTP is expired",
        "WRONG_OTP": "Entered OTP is wrong",
        "EMAIL_ALREADY_VERIFIED": "This email is already verified",
        "MOBILE_ALREADY_VERIFIED": "This Mobile is already verified",
        "EMAIL_VERIFIED": "Email is verified",
        "MOBILE_VERIFIED": "Mobile is verified",
        "LOGIN_SUCCESS": "Login Successfully",
        "INVALID_LOGIN_DETAILS": "Login credentials are invalid",
        "USERNAME_EXISTS": "Username already exists",
        "NO_ACCOUNT_FOUND": "Invalid username/email. No account exist.",
        "DELETE_SUCCESS": "Deleted Successfully",
        "TOKEN_REQUIRED":"No token provided",
        "PASSWORD_UPDATE_SUCCESS":"Password Updated successfully",
        "ADD_USER_SUCCESS":"User added successfully",
        "ADD_VOUCHER_SUCCESS":"Voucher added successfully",
        "ADD_PROMOCODE_SUCCESS":"Promocode added successfully",
        "PAGE_NOT_FOUND":"Page not found",
        "NOT_ALLOW_ACCESS_WEBSERVICES":"You does not have permission to access this api",
        "INTERNAL_SERVER_ERROR":"Internal Server Error",
	'LOGIN_SESSION_EXPIRED': "Login session expired. Please login again to continue.",
	'INVALID_USER_ACCESS': "Invalid User Access",
	'AUTH_TOKEN_MISSING': "Authorization Failed. Auth Token Missing.",
}